### ISSUE TITLE
List the benefits of using online quiz bee

### ISSUE THREAD

**Issue by samverdad** [IT3A-2016/Cypher#12]

**Comment by EarlChan** [comment]
1. Testing and quizzing online will usually provide the user with results instantly. 
2. it allows the teacher to quickly evaluate the performance of the group.
3. Tests and quizzes have always been a motivator to study harder when students know that their progress will be judged upon an exam, a performance review etc. 
4. Less Cheating on quizzes, no cheating because of time.
5. It enhance their skills in computer because its online.
6. Gain insight in the knowledge level of your target audience
