### ISSUE TITLE
Identify the specific features for host's dashboard

### ISSUE THREAD

**Issue by samverdad** [IT3A-2016/Cypher#5]

**Comment by blesanne** [comment]
Host Dashboard Features:

The best hosting services provide much more than space on a server. Deep control options and great customer support
1. Control panel
Great Web hosts feature an integrated control panel that serves up the most important administrative options in a single location. A good control panel lets you control every aspect of your website.
2.Adding Contestant
It should be very important to have this feature for the adding and removing purposes because there are some cases that different school joined unexpectedly and quite unexpectedly.
3.Creating Questioners
In this case creating a questioners by the host is very important because it will be distributed properly in every contestant because it will distribute in not a randomized question.
4.Timer Adjustment
5.Get results in less time
